set nocompatible

" my preferred leader key. Set this first so if things are binding to leader
" they bind to my leader instead of the default.
let mapleader = ","

" Load plugins
call plug#begin()
Plug 'Raimondi/delimitMate'
Plug 'chriskempson/base16-vim'
Plug 'christoomey/vim-tmux-navigator'
Plug 'mxw/vim-jsx'
Plug 'pangloss/vim-javascript'
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-pathogen'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'vim-syntastic/syntastic'
Plug 'wincent/Command-T'
call plug#end()

" set up colors
set background=dark
colorscheme base16-solarized-dark

" search options
set ignorecase " make / searches case insensitive
set smartcase " (unless they contain a capital)
set hlsearch " highlight search results
" <leader><space> to clear search
nnoremap <leader><space> :let @/=''<cr>

" tab settings
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2

" indent settings
set smartindent

syntax on

set showmode
set showcmd
set visualbell
set hidden       " enables better buffer support
set showmatch    " show matching parens
set nowrap

" make command completion more like readline
set wildmode=list:longest

" Invisible Characters
set list
set listchars=tab:>.,trail:.,extends:#,nbsp:.
noremap <Leader>i :set list!<CR> " Toggle invisible chars

" map ; to : for the quickness
nnoremap ; :

" exchange ` and '
nnoremap ' `
nnoremap ` '

" Remove trailing whitespace on save
autocmd BufWritePre * :%s/\s\+$//e

" Use `s' to insert a Single character
nnoremap s :exec "normal i".nr2char(getchar())."\e"<CR>

if has("mouse")
  set mouse=a
endif

" show line numbers
set nu

" show a little more context than the sensible.vim default
set scrolloff=3

"syntax highlighting for erb files
autocmd BufRead,BufNewFile *.erb set filetype=eruby.html

" enable spellcheck in commit messages
au BufNewFile,BufRead COMMIT_EDITMSG setlocal spell

" convert hashrockets to ruby 1.9 syntax
nmap <leader>rh :%s/\v(:)@<!:([a-zA-Z_][a-zA-Z_0-9]*)(\s*)\=\>\s?/\2:\3/gc<cr>

" easy acking
function! AckGrep(command)
  cexpr system("ack --column " . a:command)
  cw
endfunction

command! -nargs=+ -complete=file Ack call AckGrep(<q-args>)
nnoremap <leader>a :Ack<space>

" Reselect visual block after indent/outdent
vnoremap < <gv
vnoremap > >gv

" ignore existing swapfile warning
set shortmess+=A

" No splash screen
set shortmess+=I

" highlight the wrap column and column 100 (Brigade hard line length limit)
if exists('+colorcolumn')
  set colorcolumn=+0,100
  highlight ColorColumn ctermbg=black
endif

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Syntastic Settings
let g:syntastic_ruby_checkers = ['rubocop']
let g:syntastic_javascript_checkers = ['eslint']

" Always add any detected errors into the location list
let g:syntastic_always_populate_loc_list = 1

" Don't auto-open it when errors/warnings are detected, but auto-close when no
" more errors/warnings are detected.
let g:syntastic_auto_loc_list = 2

" Highlight syntax errors where possible
let g:syntastic_enable_highlighting = 1

" Show this many errors/warnings at a time in the location list
let g:syntastic_loc_list_height = 5

" Only run checkers on save, not save & quit
let g:syntastic_check_on_wq = 0

" Pretty it up a little
let g:syntastic_error_symbol = '✗'
let g:syntastic_warning_symbol = '⚠'
let g:syntastic_style_error_symbol = '⚠'
let g:syntastic_style_warning_symbol = '⚠'

" add an easy way to leave insert mode
imap jj <Esc>

" testing airline
set laststatus=2
set noshowmode
let g:airline_powerline_fonts = 1

" skip bower managed node_modules directory when searching
set wildignore+=node_modules/**
