export PATH=~/bin:$PATH
export EDITOR=vim

# keybindings
bindkey -e

## make search up and down work, so partially type and hit up/down to find relevant stuff
bindkey '^[[A' up-line-or-search
bindkey '^[[B' down-line-or-search

bindkey "^[[H" beginning-of-line
bindkey "^[[1~" beginning-of-line
bindkey "^[OH" beginning-of-line
bindkey "^[[F"  end-of-line
bindkey "^[[4~" end-of-line
bindkey "^[OF" end-of-line

# make control+arrow keys jump words
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

# Make the delete key (or Fn + Delete on the Mac) work instead of outputting a ~
bindkey '^?' backward-delete-char
bindkey "^[[3~" delete-char
bindkey "^[3;5~" delete-char
bindkey "\e[3~" delete-char

# Completion
fpath+=(~/.zshrc.d/fpath)
autoload -U compinit
zmodload -i zsh/complist
compinit

# allow lower case input to tab-complete to upper case
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}' '+l:|=* r:|=*'

# Instead of commenting a line and restoring it with the up arrow, push
# it onto the input stack with ^x; it comes back after you hit enter
bindkey "^x" push-input

# when deleting words (^w), stop on backslashes
export WORDCHARS=${WORDCHARS//[\/]}

# start a simple smtp server for debugging
alias smtpdebug="python -m smtpd -n -c DebuggingServer localhost:1025"

### heroku setup
[[ -d /usr/local/heroku/bin ]] && export PATH="/usr/local/heroku/bin:$PATH"

### lolcodes
alias rtfm='man'
alias moar='more'
alias donotwant='rm'
alias dowant='cp'
alias gtfo='mv'
alias hai='cd'

# git shortcuts
alias g='git'
alias gpsh='git push origin HEAD:$(git_current_branch)'
alias ri='git ri'

# reconnect to ssh-agent
ssh-reagent () {
 for agent in /tmp/ssh-*/agent.*; do
   echo Trying "$agent"
   export SSH_AUTH_SOCK=$agent
   if ssh-add -l > /dev/null 2>&1; then
     echo Found working SSH Agent:
     ssh-add -l
     return
   fi
 done
 echo Cannot find ssh agent - maybe you should reconnect and forward it?
}

# set up colors
autoload colors; colors;

# set up prompt
setopt prompt_subst

PROMPT='%{$fg[blue]%}%m:%{$fg[magenta]%}${PWD/#$HOME/~}
%{$fg[green]%}%(!.#.$)%{$reset_color%} '

RPROMPT='%{$fg[blue]%}[ %* ]%{$reset_color%}'

export MYSQL_PS1="\u@\h [\d]> "

for addin in $HOME/.zshrc.d/*; do
  source $addin
done

[[ -s /usr/share/fzf/key-bindings.zsh ]] && source /usr/share/fzf/key-bindings.zsh
[[ -s /usr/share/fzf/completion.zsh ]] && source /usr/share/fzf/completion.zsh

# add platform specific overrides
PLATFORM_RC=~/.zshrc.$(uname)
[[ -s $PLATFORM_RC ]] && source $PLATFORM_RC

# add overrides specific to this box / user
[[ -s ~/.zshrc.local ]] && source ~/.zshrc.local
